### ISSUE TITLE
Issue upon instance removal

### ISSUE THREAD

**Issue by Hetag1216** [Hetag1216/AreaReloader-FAWE#2]
Issue happens upon an area has finished loading and is being removed from the instances' map.

`[22:06:02 WARN]: [AreaReloader-FAWE] Task #4651 for AreaReloader-FAWE v1.1 generated an exception
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
        at java.util.ArrayList.remove(ArrayList.java:504) ~[?:?]
        at com.hedario.areareloader.fawe.AreaLoader.progressAll(AreaLoader.java:157) ~[AreaReloader-FAWE-1.1.jar:?]
        at com.hedario.areareloader.fawe.AreaLoader$1.run(AreaLoader.java:167) ~[AreaReloader-FAWE-1.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-62]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-62]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-62]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-62]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-62]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-62]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-62]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by Hetag1216** [comment]
Fixed 87a5e38
